# Generated by Django 5.0 on 2024-05-28 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_shipment_height_alter_shipment_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='Height',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Length',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Weight',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Width',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='transporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.transporter'),
        ),
    ]
