# Generated by Django 5.0 on 2024-05-30 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_shipment_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='quote',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_who_created_a_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='transporter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporter_who_accepted_the_shipment', to='product.transporter'),
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(auto_created=True)),
                ('quote', models.IntegerField()),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporter_who_gave_quote', to='product.transporter')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='quotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporter_who_accepted_the_shipment', to='product.quotes'),
        ),
    ]
