# Generated by Django 5.0.6 on 2024-06-01 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_shipment_customer_alter_shipment_quotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_for_which_quote_is_given', to='product.shipment'),
        ),
    ]
