# Generated by Django 5.0.6 on 2024-06-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_quotes_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='unique_id',
        ),
    ]
