# Generated by Django 5.0 on 2024-06-03 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_quotes_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='transporter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporter_who_gave_quote', to='product.transporter'),
        ),
    ]
