# Generated by Django 5.0 on 2024-06-03 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_quotes_transporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporter_who_gave_quote', to='product.transporter'),
        ),
        migrations.AlterUniqueTogether(
            name='quotes',
            unique_together={('transporter', 'shipment')},
        ),
    ]
