# Generated by Django 5.0 on 2024-06-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_quotes_transporter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='d_pincode',
            field=models.IntegerField(default=600012),
        ),
        migrations.AddField(
            model_name='shipment',
            name='earliest_delivery_date',
            field=models.DateField(default='2024-06-19'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='earliest_pickup_date',
            field=models.DateField(default='2024-06-20'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='latest_delivery_date',
            field=models.DateField(default='2024-06-24'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='latest_pickup_date',
            field=models.DateField(default='2024-06-27'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='p_pincode',
            field=models.IntegerField(default=600012),
        ),
        migrations.AddField(
            model_name='shipment',
            name='title',
            field=models.CharField(default='acer computer', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_for_which_quote_is_given', to='product.shipment'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transporter_who_gave_quote', to='product.transporter'),
        ),
    ]
