# Generated by Django 5.0 on 2024-06-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_shipment_d_pincode_shipment_earliest_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='earliest_delivery_date',
            field=models.DateField(default='2024-06-19'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='earliest_pickup_date',
            field=models.DateField(default='2024-06-12'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='latest_delivery_date',
            field=models.DateField(default='2024-06-32'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='latest_pickup_date',
            field=models.DateField(default='2024-06-15'),
        ),
    ]
