# Generated by Django 5.0 on 2024-06-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_shipment_earliest_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='latest_delivery_date',
            field=models.DateField(default='2024-06-20'),
        ),
    ]
