# Generated by Django 5.0 on 2024-06-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_shipment_latest_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shipment_photos/'),
        ),
    ]
