# Generated by Django 5.0 on 2024-06-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_shipment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
