# Generated by Django 5.0 on 2024-06-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_shipment_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='quotes',
        ),
    ]
