# Generated by Django 5.0 on 2024-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_shipment_transporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
