# Generated by Django 5.0 on 2024-06-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_shipment_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='Drop',
            field=models.CharField(default='Drop', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Pickup',
            field=models.CharField(default='Pick', max_length=50),
        ),
    ]
