# Generated by Django 5.0 on 2024-06-21 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_shipment_drop_alter_shipment_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_for_which_quote_is_given', to='product.shipment'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transporter_who_gave_quote', to='product.transporter'),
        ),
    ]
