# Generated by Django 5.0 on 2024-06-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_quotes_shipment_alter_quotes_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
