# Generated by Django 5.0 on 2024-06-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_shipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
